### ISSUE TITLE
Validator name in Validator detail page looks like a link

### ISSUE THREAD

**Issue by sbhargava** [solana-labs/networkexplorer#451] opened 2019-09-27 21:36 UTC
<img width="842" alt="Screen Shot 2019-09-27 at 2 34 20 PM" src="https://user-images.githubusercontent.com/1693710/65803656-0fbb6880-e134-11e9-8743-8a0e8c5e3604.png">

Minor, but probably for good, consistent UI, we should not make the name look like a link or link it to maybe their keybase profile?

**Comment by CriesofCarrots** [comment] 2019-09-27 21:37
So does address, which I suppose could be a link, but would link back to this same page. How to handle?

**Comment by manuel-calavera** [comment] 2019-10-04 15:34
@sbhargava what do we want here exactly?

**Comment by manuel-calavera** [comment] 2019-10-04 15:35
@CriesofCarrots @sbhargava closing as a duplicate of #445

**Closed by manuel-calavera** 2019-10-04 15:35 UTC
